//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shadownaives.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("shadownaives.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 @echo off
        ///
        ///echo 1.Create Naive Service Config
        ///set nnp=%cd%
        ///:xml
        ///(
        ///echo ^&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?^&gt;
        ///echo ^&lt;service^&gt;
        ///echo     ^&lt;id^&gt;nnp_naive^&lt;/id^&gt;
        ///echo     ^&lt;name^&gt;nnp_naive^&lt;/name^&gt;
        ///echo     ^&lt;description^&gt;Naive Client Service^&lt;/description^&gt;
        ///echo     ^&lt;logpath^&gt;%nnp%\naive\logs^&lt;/logpath^&gt;
        ///echo     ^&lt;log mode=&quot;roll-by-size&quot;^&gt;
        ///echo         ^&lt;sizeThreshold^&gt;10240^&lt;/sizeThreshold^&gt;
        ///echo         ^&lt;keepFiles^&gt;8^&lt;/keepFiles^&gt;
        ///echo     ^&lt;/log^&gt;
        ///echo     ^&lt;executable^&gt;%nnp%\naive\na [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] naive {
            get {
                object obj = ResourceManager.GetObject("naive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] naive_service {
            get {
                object obj = ResourceManager.GetObject("naive_service", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;startup&gt;
        ///        &lt;supportedRuntime version=&quot;v2.0.50727&quot; /&gt;
        ///    &lt;/startup&gt;
        ///    &lt;runtime&gt;
        ///        &lt;generatePublisherEvidence enabled=&quot;false&quot; /&gt;
        ///    &lt;/runtime&gt;
        ///&lt;/configuration&gt; 的本地化字符串。
        /// </summary>
        internal static string naive_service_exe {
            get {
                return ResourceManager.GetString("naive_service_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] proxy {
            get {
                object obj = ResourceManager.GetObject("proxy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] readme {
            get {
                object obj = ResourceManager.GetObject("readme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 @echo off
        ///
        ///echo 1. Stop Nginx Service
        ///net stop nnp_nginx
        ///echo.
        ///
        ///echo 2. Stop Naive Service
        ///net stop nnp_naive
        ///echo.
        ///
        ///echo 3. Delete Nginx Service
        ///sc delete nnp_nginx
        ///echo. 
        ///
        ///echo 4. Delete Naive Service
        ///sc delete nnp_naive
        ///echo.
        ///
        ///echo 5. Delete Service Config
        ///DEL /Q /F /S naive\naive-service.xml 
        ///DEL /Q /F /S naive\logs
        ///DEL /Q /F /S nginx\nginx-service.xml
        ///DEL /Q /F /S nginx\logs
        ///DEL /Q /F /S naive.ini
        ///rd /s /q naive
        ///rd /s /q nginx
        ///echo.
        ///exit 的本地化字符串。
        /// </summary>
        internal static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
    }
}
