//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shadownaive.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("shadownaive.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 // Generated by gfwlist2pac in precise mode
        ///// https://github.com/clowwindy/gfwlist2pac
        ///
        ///var proxy = &quot;SOCKS5 __SOCKS5ADDR__:__SOCKS5PORT__; SOCKS __SOCKS5ADDR__:__SOCKS5PORT__; DIRECT;&quot;;
        ///
        ///var rules = __RULES__;
        ///
        ////*
        /// * This file is part of Adblock Plus &lt;http://adblockplus.org/&gt;,
        /// * Copyright (C) 2006-2014 Eyeo GmbH
        /// *
        /// * Adblock Plus is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU General Public License version 3 as
        /// * published by the Free Software Foundation.
        /// *
        /// *  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string abp {
            get {
                return ResourceManager.GetString("abp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [AutoProxy 0.2.9]
        ///! Checksum: r4SYSZr5/Ull/SHPPTQ/mg
        ///! Expires: 6h
        ///! Title: GFWList4LL
        ///! GFWList with EVERYTHING included
        ///! Last Modified: Sat, 29 Oct 2022 22:47:21 -0400
        ///!
        ///! HomePage: https://github.com/gfwlist/gfwlist
        ///! License: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
        ///!
        ///! GFWList is unlikely to fully comprise the real
        ///! rules being deployed inside GFW system. We try
        ///! our best to keep the list up to date. Please
        ///! contact us regarding URL submission / removal,
        ///! or suggestion / enhancement  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string gfwlist {
            get {
                return ResourceManager.GetString("gfwlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] proxy {
            get {
                object obj = ResourceManager.GetObject("proxy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string user_rule {
            get {
                return ResourceManager.GetString("user_rule", resourceCulture);
            }
        }
    }
}
